---
abstract: 'Scope database transactions on DBI handles in code, to detect and prevent issues with unterminated transactions.'
author:
  - 'Guillaume Aubert <aubertg@cpan.org>'
build_requires:
  Carp: 0
  DBD::SQLite: 0
  DBI: 0
  Data::Dumper: 0
  Data::Validate::Type: 0
  File::Spec: 0
  Test::Exception: 0
  Test::More: 0
  Try::Tiny: 0
configure_requires:
  Module::Build: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.4, CPAN::Meta::Converter version 2.120530'
license: artistic
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: DBIx-ScopedTransaction
provides:
  DBIx::ScopedTransaction:
    file: lib/DBIx/ScopedTransaction.pm
    version: v1.0.3
requires:
  perl: 5.006
resources:
  bugtracker: http://rt.cpan.org/NoAuth/ReportBug.html?Queue=dbix-scopedtransaction
  homepage: https://metacpan.org/release/DBIx-ScopedTransaction
  license: http://opensource.org/licenses/artistic-license.php
  repository: https://sourceforge.net/p/perltransaction/code
version: v1.0.3
